config:
  inputs: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Tag              kube.<namespace_name>.<pod_name>.<container_name>
        Tag_Regex        (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
        multiline.parser docker, cri
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.
        Regex_Parser        k8s-custom-tag
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On 
        
  customParsers: |
    [PARSER]
        Name    k8s-custom-tag
        Format  regex
        Regex   ^(?<namespace_name>[^_]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)\.(?<container_name>.+)\.log$      
        
  outputs: |
    [OUTPUT]
        Name               cloudwatch_logs
        Match              kube.*
        region             eu-central-1
        log_group_name     fluent-bit-cloudwatch
        log_stream_prefix  lifi.
        log_retention_days 30
        auto_create_group  On 

serviceAccount:
  create: false
  name: fluentbit-cloudwatch-sa
serviceMonitor:
  enabled: true
  namespace: kube-prometheus-stack
  jobLabel: fluentbit
  selector:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
dashboards:
  enabled: true
