apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifi-nodeapp
  labels:
    app: lifi-nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lifi-nodeapp
  template:
    metadata:
      labels:
        app: lifi-nodeapp
    spec:
      containers:
      - name: lifi-nodeapp
        image: $ECR_REGISTRY/$ECR_REPOSITORY:dev-${{ github.run_number }} #patched from github action
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 250m
            memory: "64Mi"
          limits:
            cpu: 500m
            memory: "128Mi"
            